# Generated by Django 6.1.1 on 2026-09-15 21:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ciclo escolar',
                'verbose_name_plural': 'ciclos escolares',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('orden', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'grado',
                'verbose_name_plural': 'grados',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('parentesco', models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('tutor', 'Tutor'), ('otro', 'Otro')], default='tutor', max_length=20)),
                ('telefono_whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('recibe_notificaciones', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tutor',
                'verbose_name_plural': 'tutores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='asistencias.cicloescolar')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='asistencias.grado')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'ordering': ['grado__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('nombres', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(blank=True, max_length=80)),
                ('codigo_qr', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='asistencias.grupo')),
                ('tutores', models.ManyToManyField(blank=True, related_name='alumnos', to='asistencias.tutor')),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora', models.TimeField(default=django.utils.timezone.localtime)),
                ('estado', models.CharField(choices=[('a_tiempo', 'A tiempo'), ('retardo', 'Retardo'), ('justificado', 'Justificado'), ('manual', 'Manual')], default='a_tiempo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_asistencia', to='asistencias.alumno')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_asistencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de asistencia',
                'verbose_name_plural': 'registros de asistencia',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('telefono_destino', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('respuesta_proveedor', models.TextField(blank=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_whatsapp', to='asistencias.registroasistencia')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_whatsapp', to='asistencias.tutor')),
            ],
            options={
                'verbose_name': 'notificacion de WhatsApp',
                'verbose_name_plural': 'notificaciones de WhatsApp',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('grado', 'nombre', 'ciclo_escolar'), name='grupo_unico_por_ciclo'),
        ),
        migrations.AddConstraint(
            model_name='registroasistencia',
            constraint=models.UniqueConstraint(fields=('alumno', 'fecha', 'tipo'), name='registro_unico_por_alumno_fecha_tipo'),
        ),
    ]
