# Generated by Django 6.1.1 on 2026-09-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='codigo_nfc',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
