# Generated by Django 6.1.1 on 2026-09-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_alumno_codigo_nfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('a_tiempo', 'A tiempo'), ('retardo', 'Retardo'), ('justificado', 'Justificado'), ('ausente', 'Ausente'), ('manual', 'Manual')], default='a_tiempo', max_length=20),
        ),
    ]
