# Generated by Django 6.1.1 on 2026-10-05 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0007_direccion_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('suspension', 'Suspension oficial'), ('vacaciones', 'Vacaciones'), ('receso', 'Receso escolar'), ('consejo', 'Consejo Tecnico'), ('informativo', 'Actividad escolar'), ('cancelacion', 'Cancelacion de Direccion')], max_length=20)),
                ('descripcion', models.CharField(max_length=160)),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_escolares', to='asistencias.cicloescolar')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'tipo'],
                'constraints': [models.UniqueConstraint(fields=('ciclo_escolar', 'fecha', 'tipo'), name='dia_escolar_unico_por_tipo')],
            },
        ),
    ]
