# Generated by Django 6.1.1 on 2026-10-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0010_registro_calificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaescolar',
            name='tipo',
            field=models.CharField(choices=[('suspension', 'Suspension oficial'), ('vacaciones', 'Vacaciones'), ('receso', 'Receso escolar'), ('consejo', 'Consejo Tecnico'), ('registro', 'Registro de calificaciones'), ('informativo', 'Actividad escolar'), ('cancelacion', 'Cancelacion de Direccion')], max_length=20),
        ),
    ]
