# Generated by Django 6.1.1 on 2026-10-06 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0012_eventoescolar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='asistencias.alumno')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_alumno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta de alumno',
                'verbose_name_plural': 'cuentas de alumnos',
            },
        ),
    ]
