# Generated by Django 6.1.1 on 2026-10-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0015_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='recibe_notificaciones',
            field=models.BooleanField(default=False),
        ),
    ]
